# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Model-DBIDM
version:      0.01
version_from: lib/Catalyst/Model/DBIDM.pm
installdirs:  site
requires:
    Catalyst::Model:               0
    DBI:                           0
    DBIx::DataModel:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
