---
name: Catalyst-Model-DBIDM
version: 0.03
author:
  - 'Cedric Bouvier <cbouvi@cpan.org>'
abstract: DBIx::DataModel model class
license: perl
build_requires:
  Catalyst::Model: 0
  DBI: 0
  DBIx::DataModel: 0
  Test::More: 0
provides:
  Catalyst::Helper::Model::DBIDM:
    file: lib/Catalyst/Helper/Model/DBIDM.pm
    version: 0.01
  Catalyst::Model::DBIDM:
    file: lib/Catalyst/Model/DBIDM.pm
    version: 0.03
generated_by: Module::Build version 0.26
